name: Deploy to Production

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build app
        run: npm install && npm run build

      - name: Check build status and deploy app
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Build succeeded"
            cd ../..
            cd ..
            sudo git pull https://${{ secrets.User_Name }}:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/JS-Tigers/gifts-reco.git prod
            sudo npm install
            sudo npm run build
            sudo pm2 restart mvHackathonBuild
          fi